global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # prometheus service
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # proxy service
  - job_name: proxy
    static_configs:
      - targets: ['proxy:8080']